Repository SciCatProject/scicat-backend-next, pull requests merged in 2023-09, with the labels that each got.

#719 E2e fix
  .github/workflows/test.yml
  CI/E2E/docker-compose.yaml
Labels: testing, FE-updates, Important

#718 Libs upgrade
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/strategies/ldap.strategy.ts
  src/auth/strategies/local.strategy.ts
  src/auth/strategies/oidc.strategy.ts
  src/datasets/datasets.controller.ts
  src/instruments/instruments.controller.ts
  src/origdatablocks/origdatablocks.controller.ts
  src/users/interceptors/create-user-settings.interceptor.ts
  src/users/user-identities.controller.ts
  src/users/users.controller.ts
Labels: dependencies

#722 github: use nodeversion in cache key
  .github/workflows/test.yml
Labels: github_actions, testing

#725 Fix: saving logbook token in memory
  .env.example
  CI/E2E/.env.backend-next
  CI/E2E/.env.scichat-loopback
  CI/E2E/backend.env
  README.md
  src/config/configuration.ts
  src/logbooks/logbooks.service.spec.ts
  src/logbooks/logbooks.service.ts
Labels: refactoring
