Repository SciCatProject/scicat-backend-next, pull requests merged in 2024-12, with the labels that each got.

#1532 feat: allow custom dataset types defined in configuration
  .env.example
  .github/workflows/test.yml
  .gitignore
  datasetTypes.example.json
  src/config/configuration.ts
  src/datasets/datasets.controller.ts
  src/datasets/datasets.module.ts
  src/datasets/dto/create-dataset.dto.ts
  src/datasets/dto/update-dataset.dto.ts
  src/datasets/schemas/dataset.schema.ts
  test/DatasetCustom.js
  test/TestData.js
Labels: DCS

#1542 chore: revert packge-lock changes and update minor versions of the pa…
  package-lock.json
Labels: bug, dependencies

#1575 Jobs RabbitMQ Action connection info should come from ConfigService
  .env.example
  jobConfig.example.yaml
  package-lock.json
  package.json
  src/common/common.module.ts
  src/common/rabbitmq/rabbitmq.module.ts
  src/common/rabbitmq/rabbitmq.service.ts
  src/config/configuration.ts
  src/config/job-config/actions/rabbitmqaction/rabbitmqaction.interface.ts
  src/config/job-config/actions/rabbitmqaction/rabbitmqaction.module.ts
  src/config/job-config/actions/rabbitmqaction/rabbitmqaction.service.ts
  src/config/job-config/actions/rabbitmqaction/rabbitmqaction.ts
Labels: Release Jobs
