Repository SciCatProject/scicat-backend-next, pull requests merged in 2024-11, with the labels that each got.

#1487 fix: fixed output dataset dtos in swagger
  src/datasets/datasets.controller.ts
Labels: bug

#1499 feat: add parent proposal to the proposal document
  src/proposals/dto/update-proposal.dto.ts
  src/proposals/proposals.controller.ts
  src/proposals/schemas/proposal.schema.ts
  src/samples/samples.controller.ts
  src/users/users.controller.spec.ts
  src/users/users.controller.ts
  test/Proposal.js
  test/ProposalAuthorization.js
  test/RawDataset.js
  test/TestData.js
Labels: feature, DCS

#1503 feat: add type property to the proposal document with database migration
  .env.example
  .github/workflows/test.yml
  .gitignore
  README.md
  migrations/20241113130700-proposal-type.js
  package.json
  proposalTypes.example.json
  src/config/configuration.ts
  src/proposals/dto/update-proposal.dto.ts
  src/proposals/proposals.module.ts
  src/proposals/proposals.service.ts
  src/proposals/schemas/proposal.schema.ts
  test/Proposal.js
Labels: feature, DCS

#1506 feat: proposal metadata and tests
  src/proposals/schemas/proposal.schema.ts
  test/Proposal.js
Labels: testing, DCS
