Repository SciCatProject/scicat-backend-next, pull requests merged in 2025-01, with the labels that each got.

#1559 feat(metrics): add metrics logging and configuration support
  .gitignore
  metricsConfig.example.json
  src/app.module.ts
  src/config/configuration.ts
  src/main.ts
  src/metrics/metrics.module.ts
  src/metrics/middlewares/accessTracking.middleware.ts
Labels: feature

#1581 RabbitMQ service: fix logging and error handling
  src/common/common.module.ts
  src/common/rabbitmq/rabbitmq.service.ts
  src/config/job-config/actions/rabbitmqaction/rabbitmqaction.module.ts
  src/config/job-config/actions/rabbitmqaction/rabbitmqaction.service.ts
  src/config/job-config/actions/rabbitmqaction/rabbitmqaction.ts
Labels: Release Jobs

#1628 feat: support Microsoft Graph API for emails
  .env.example
  README.md
  src/app.module.ts
  src/common/graph-mail.ts
  src/config/configuration.ts
Labels: feature

#1672 refactor: proposal count endpoint
  src/common/types.ts
  src/proposals/proposals.controller.ts
  src/proposals/proposals.service.ts
Labels: DCS

#1674 fix: datasets fullquery output dto
  src/datasets/datasets.controller.ts
Labels: bug
