Repository SciCatProject/scicat-backend-next, pull requests merged in 2025-05, with the labels that each got.

#1745 fix: access permissions for attachments when provided in the related dataset fields
  src/datasets/datasets-access.service.ts
Labels: bug, DCS

#1830 feat: make frontend config and theme file locations configurable
  .env.example
  README.md
  docs/frontend-config-guide/dynamic-dataset-detail-component.md
  src/admin/admin.service.spec.ts
  src/admin/admin.service.ts
  src/config/configuration.ts
Labels: enhancement, DCS, Discussion needed

#1887 feat: implement user password update functionality with validation
  src/common/types.ts
  src/users/dto/update-user-password.dto.ts
  src/users/users.controller.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
  test/Users.js
Labels: review: please
