Repository SciCatProject/scicat-backend-next, pull requests merged in 2025-03, with the labels that each got.

#1754 refactor: remove RabbitMQ integration and related logic from App Module
  src/app.module.ts
Labels: review: please

#1758 feat(jobs): fix ownerUser, contactEmail logic and datasetList validation
  src/jobs/dto/create-job.dto.ts
  src/jobs/jobs.controller.ts
  test/Jobs.js
  test/JobsAll.js
  test/JobsAuthenticated.js
  test/JobsDatasetAccess.js
  test/JobsDatasetOwner.js
  test/JobsDatasetPublic.js
  test/JobsSpecificGroup.js
  test/JobsSpecificUser.js
Labels: Release Jobs

#1770 feat(jobs): replace ApiProperty with openapi cli-plugin
  nest-cli.json
  src/common/handlebars-helpers.ts
  src/jobs/dto/create-job.dto.ts
  src/jobs/dto/update-job.dto.ts
  src/jobs/schemas/job.schema.ts
Labels: Release Jobs

#1760 style: update frontend theme to match the new branding colors
  src/config/frontend.theme.json
Labels: FE-updates

#1704 fix: update to readme
  README.md
Labels: documentation, DCS
